import { Notifications } from "@mantine/notifications";
import "@mantine/notifications/styles.css";
import TopHeader from "@/components/top/header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TopHeader>
      <Notifications position="bottom-right" />
      {children}
    </TopHeader>
  );
}
