import DashboardLayout from "@/components/layout/dashboard";
import type { Metadata } from "next";
import { getSession } from "@/components/hooks/useSession";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  return (
    <html lang="ja">
      <body>
        <DashboardLayout session={session}>{children}</DashboardLayout>
      </body>
    </html>
  );
}